stages:
  - deploy

deploy:prod:
  stage: deploy
  image: python:3
  tags:
    - ansible
  script:
    - 'pip install ansible'
    - 'chmod -R 750 ansible'
    - 'cd ansible'
    - 'ansible-playbook --private-key=/id_rsa site.yml'
  only:
    - master
