---
- name: Install/Update Hugo
  snap:
    name: "hugo"
    channel: "extended/stable"
    state: present

- name: Clear the old temporary folder
  file:
    state: absent
    path: "{{ tmp_dir }}/"

- name: Create a temporary folder
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755

- name: Clone the latest site
  git:
    repo: https://git.tdude.co/tristan/www.tdude.co.git
    dest: "{{ tmp_dir }}"

- name: Generate the site
  command: "/snap/bin/hugo"
  args:
    chdir: "{{ tmp_dir }}"

- name: Set permissions
  file:
    path: "{{ tmp_dir }}/public"
    state: directory
    owner: deploy
    group: www-data
    mode: 0755
    recurse: true

- name: Clear the old webroot
  file:
    state: absent
    path: "{{ webroot }}/"

- name: Copy the site to the webroot
  synchronize:
    src: "{{ tmp_dir }}/public/"
    dest: "{{ webroot }}"
    owner: true
    group: true
    perms: true
  delegate_to: "{{ inventory_hostname }}"

- name: Clear the old temporary folder
  file:
    state: absent
    path: "{{ tmp_dir }}/"